### ISSUE TITLE
Certificate is revoked

### ISSUE THREAD

**Issue by mdarse** [cloudfoundry-community/xip-release#1]
Going to [https://sslip.io]() lead to a certificate error:
<img width="529" alt="capture d ecran 2015-09-08 a 15 28 48" src="https://cloud.githubusercontent.com/assets/484720/9735952/b38ef5a6-563e-11e5-82e2-c514c8af80cf.png">

**Comment by westi** [comment]
I think you have filed this against the wrong repo - https://github.com/cunnie/sslip.io/issues/2 - looks like the right issue.

**Comment by cunnie** [comment]
@mdarse,

Thanks for the tip—Hacker News did a great job of informing me that the certificate was revoked, and Comodo made it clear to me, in no uncertain terms, that they would not reissue the certificate if I shared the key. (they did reissue the certificate, and I have not shared the new key outside my company). Or, in French, _Merci beaucoups Matthieu, j'etait vraiment desolées quand ils ont revoqué mon certificat_

@westi 

This repo is the correct one to open issues. I need to become better at monitoring my GitHub repos (I'm subscribed to so many repos through work that my personal ones are drowned out in the noise). In other words, sorry for the lag.

—Brian
