### ISSUE TITLE
Rename to sslip-boshrelease 

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-community/xip-release#2]
looks like the underlying project is called sslip so perhaps rename the boshrelease to match?

**Comment by drnic** [comment]
Hmm sslip isn't a package - so perhaps I'm wrong about the assumption - was this project a precursor to/experiment before sslip?

**Comment by cunnie** [comment]
Hi @drnic ,

The BOSH release is named  _xip-release_, but we could have just as easily called it _sslip-release_ or _PowerDNS-release_. We went with _xip-release_ for 2 reasons:
- this release provides only the xip.io functionality (with slight tweaks, but basically it's Sam Stephenson's code wrapped in a BOSH release). The thing that sslip.io offered was a wildcard certificate, but the certificate was orthogonal to the release (i.e. it had nothing to do with the release itself).
- people are more familiar with xip.io than with sslip.io

That being said, I believe there was a point where we called the release _sslip-release_, so you may find artifacts of the earlier name.
